sudo: false
language: node_js
node_js:
  - stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  firefox: latest

after_success:
  - bash <(curl -s https://codecov.io/bash)
